/*
   This file was generated automatically by the Mojo IDE version B1.2.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu8bit_29 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] aluout
  );
  
  
  
  reg [7:0] xb;
  
  integer i;
  
  always @* begin
    
    case (alufn)
      6'h00: begin
        xb = b;
        aluout = a + xb;
      end
      6'h01: begin
        xb = ~b + 1'h1;
        aluout = a + xb;
      end
      6'h02: begin
        aluout = a * b;
      end
      6'h0f: begin
        if (a[7+0-:1] == 1'h0) begin
          aluout = a;
        end else begin
          aluout = ~(a - 1'h1);
        end
      end
      6'h18: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if (a[(i)*1+0-:1] == 1'h1 && b[(i)*1+0-:1] == 1'h1) begin
            aluout[(i)*1+0-:1] = 1'h1;
          end else begin
            aluout[(i)*1+0-:1] = 1'h0;
          end
        end
      end
      6'h1e: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if (a[(i)*1+0-:1] == 1'h1 || b[(i)*1+0-:1] == 1'h1) begin
            aluout[(i)*1+0-:1] = 1'h1;
          end else begin
            aluout[(i)*1+0-:1] = 1'h0;
          end
        end
      end
      6'h16: begin
        for (i = 1'h0; i < 4'h8; i = i + 1) begin
          if ((a[(i)*1+0-:1] == 1'h1 && b[(i)*1+0-:1] == 1'h0) || (a[(i)*1+0-:1] == 1'h0 && b[(i)*1+0-:1] == 1'h1)) begin
            aluout[(i)*1+0-:1] = 1'h1;
          end else begin
            aluout[(i)*1+0-:1] = 1'h0;
          end
        end
      end
      6'h1a: begin
        aluout = a;
      end
      6'h20: begin
        aluout = a << b;
      end
      6'h21: begin
        aluout = a >> b;
      end
      6'h23: begin
        aluout = $signed(a) >>> b;
      end
      6'h33: begin
        if (a == b) begin
          aluout = 1'h1;
        end else begin
          aluout = 1'h0;
        end
      end
      6'h35: begin
        if (a < b) begin
          aluout = 1'h1;
        end else begin
          aluout = 1'h0;
        end
      end
      6'h37: begin
        if (a <= b) begin
          aluout = 1'h1;
        end else begin
          aluout = 1'h0;
        end
      end
      default: begin
        aluout = 8'h01;
      end
    endcase
  end
endmodule
