/*
   This file was generated automatically by the Mojo IDE version B1.2.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 3
     DIV = 25
     BOTTOM = 0
     UP = 0
*/
module countdowntimer_52 (
    input clk,
    input rst,
    input start,
    output reg timerdone,
    output reg [2:0] value
  );
  
  localparam SIZE = 2'h3;
  localparam DIV = 5'h19;
  localparam BOTTOM = 1'h0;
  localparam UP = 1'h0;
  
  
  reg [27:0] M_ctr_d, M_ctr_q = 28'hbffffff;
  
  localparam MIN_VALUE = 26'h1ffffff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    timerdone = 1'h0;
    value = M_ctr_q[25+2-:3];
    if (1'h1) begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (M_ctr_q == 26'h1ffffff) begin
        M_ctr_d = 28'hbffffff;
        timerdone = 1'h1;
      end
    end
    if (start) begin
      M_ctr_d = 28'hbffffff;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 28'hbffffff;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
