/*
   This file was generated automatically by the Mojo IDE version B1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gametwosequencerom_56 (
    input [3:0] address,
    output reg [29:0] sequence
  );
  
  
  
  localparam SEQUENCEDATA = 480'h05408008020a41404824024090881401029048111282414025028122a444290510282905002128200542402412054221200205428008090501002805;
  
  always @* begin
    sequence = SEQUENCEDATA[(address)*30+29-:30];
  end
endmodule
