/*
   This file was generated automatically by the Mojo IDE version B1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gametwoplayer_53 (
    input clk,
    input rst,
    input correct,
    input start,
    input nextround,
    input [2:0] playerbuttons,
    output reg [7:0] playerscore,
    output reg [29:0] answer
  );
  
  
  
  wire [8-1:0] M_scorectr_value;
  reg [1-1:0] M_scorectr_upcounter;
  reg [1-1:0] M_scorectr_start;
  conditionalcounter_69 scorectr (
    .clk(clk),
    .rst(rst),
    .upcounter(M_scorectr_upcounter),
    .start(M_scorectr_start),
    .value(M_scorectr_value)
  );
  wire [4-1:0] M_answerctr_value;
  reg [1-1:0] M_answerctr_upcounter;
  reg [1-1:0] M_answerctr_start;
  conditionalcounter_70 answerctr (
    .clk(clk),
    .rst(rst),
    .upcounter(M_answerctr_upcounter),
    .start(M_answerctr_start),
    .value(M_answerctr_value)
  );
  wire [30-1:0] M_gametwoinput_response;
  reg [1-1:0] M_gametwoinput_start;
  reg [1-1:0] M_gametwoinput_red;
  reg [1-1:0] M_gametwoinput_green;
  reg [1-1:0] M_gametwoinput_blue;
  reg [4-1:0] M_gametwoinput_pressnumber;
  gametwoinput_71 gametwoinput (
    .clk(clk),
    .rst(rst),
    .start(M_gametwoinput_start),
    .red(M_gametwoinput_red),
    .green(M_gametwoinput_green),
    .blue(M_gametwoinput_blue),
    .pressnumber(M_gametwoinput_pressnumber),
    .response(M_gametwoinput_response)
  );
  
  always @* begin
    M_gametwoinput_red = playerbuttons[0+0-:1];
    M_gametwoinput_green = playerbuttons[1+0-:1];
    M_gametwoinput_blue = playerbuttons[2+0-:1];
    M_gametwoinput_pressnumber = M_answerctr_value;
    answer = M_gametwoinput_response;
    M_scorectr_start = 1'h0;
    M_answerctr_start = 1'h0;
    M_gametwoinput_start = 1'h0;
    M_scorectr_upcounter = 1'h0;
    M_answerctr_upcounter = 1'h0;
    if (start) begin
      M_scorectr_start = 1'h1;
    end
    if (nextround) begin
      M_answerctr_start = 1'h1;
      M_gametwoinput_start = 1'h1;
    end
    if (correct) begin
      M_scorectr_upcounter = 1'h1;
    end
    playerscore = M_scorectr_value;
    if (playerbuttons[0+0-:1]) begin
      M_answerctr_upcounter = 1'h1;
    end
    if (playerbuttons[1+0-:1]) begin
      M_answerctr_upcounter = 1'h1;
    end
    if (playerbuttons[2+0-:1]) begin
      M_answerctr_upcounter = 1'h1;
    end
  end
endmodule
