/*
   This file was generated automatically by the Mojo IDE version B1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 30
     DIV = 0
     TOP = 0
*/
module gametwoinput_75 (
    input clk,
    input rst,
    input start,
    input red,
    input green,
    input blue,
    input [3:0] pressnumber,
    output reg [29:0] response
  );
  
  localparam SIZE = 5'h1e;
  localparam DIV = 1'h0;
  localparam TOP = 1'h0;
  
  
  reg [29:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    response = M_ctr_q[0+29-:30];
    
    case (pressnumber)
      1'h0: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000001;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00000400;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h00100000;
        end
      end
      1'h1: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000002;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00000800;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h00200000;
        end
      end
      2'h2: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000004;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00001000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h00400000;
        end
      end
      2'h3: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000008;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00002000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h00800000;
        end
      end
      3'h4: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000010;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00004000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h01000000;
        end
      end
      3'h5: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000020;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00008000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h02000000;
        end
      end
      3'h6: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000040;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00010000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h04000000;
        end
      end
      3'h7: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000080;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00020000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h08000000;
        end
      end
      4'h8: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000100;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00040000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h10000000;
        end
      end
      4'h9: begin
        if (red) begin
          M_ctr_d = M_ctr_q + 30'h00000200;
        end
        if (green) begin
          M_ctr_d = M_ctr_q + 30'h00080000;
        end
        if (blue) begin
          M_ctr_d = M_ctr_q + 30'h20000000;
        end
      end
    endcase
    if (start) begin
      M_ctr_d = 30'h00000000;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
