/*
   This file was generated automatically by the Mojo IDE version B1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gametwocentralleddisplay_51 (
    input clk,
    input rst,
    input [29:0] sequence,
    input start,
    output reg [2:0] leddisplay,
    output reg displayfinish
  );
  
  
  
  wire [4-1:0] M_leddisplayctr_value;
  reg [1-1:0] M_leddisplayctr_start;
  leddisplaycounter_73 leddisplayctr (
    .clk(clk),
    .rst(rst),
    .start(M_leddisplayctr_start),
    .value(M_leddisplayctr_value)
  );
  
  always @* begin
    displayfinish = 1'h0;
    leddisplay = 1'h0;
    M_leddisplayctr_start = 1'h0;
    if (start) begin
      M_leddisplayctr_start = 1'h1;
    end
    
    case (M_leddisplayctr_value)
      4'ha: begin
        displayfinish = 1'h1;
      end
      default: begin
        if (sequence[(M_leddisplayctr_value)*1+0-:1]) begin
          leddisplay = 3'h4;
        end else begin
          if (sequence[(4'ha + M_leddisplayctr_value)*1+0-:1]) begin
            leddisplay = 3'h2;
          end else begin
            if (sequence[(5'h14 + M_leddisplayctr_value)*1+0-:1]) begin
              leddisplay = 3'h1;
            end else begin
              displayfinish = 1'h1;
            end
          end
        end
      end
    endcase
  end
endmodule
