/*
   This file was generated automatically by the Mojo IDE version B1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 8
     DIV = 0
     BOTTOM = 0
     UP = 0
*/
module gameonedecreasecounter_48 (
    input clk,
    input rst,
    input start,
    input decrease,
    input [1:0] decreaseamount,
    input [7:0] aluout,
    output reg [7:0] alub,
    output reg [5:0] alufn,
    output reg gameone_end,
    output reg gameone_lose,
    output reg [7:0] remainder
  );
  
  localparam SIZE = 4'h8;
  localparam DIV = 1'h0;
  localparam BOTTOM = 1'h0;
  localparam UP = 1'h0;
  
  
  reg [7:0] M_ctr_d, M_ctr_q = 8'h1e;
  
  localparam MIN_VALUE = 1'h0;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    alufn = 6'h01;
    alub = 1'h0;
    gameone_end = 1'h0;
    gameone_lose = 1'h0;
    remainder = M_ctr_q[0+7-:8];
    if (start) begin
      M_ctr_d = 8'h1e;
    end
    if (1'h1) begin
      if (decrease) begin
        alub = decreaseamount;
        M_ctr_d = aluout;
      end
      if (M_ctr_q == 1'h0) begin
        gameone_end = 1'h1;
      end
      if (M_ctr_q > 8'h1e) begin
        gameone_lose = 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 8'h1e;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
